# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dyLszs6n7a4l_tuAtPHzjlGS_RJwQZBY
"""

import requests

# Define the API endpoint
API_URL = "https://inf.cl.uni-trier.de/chat/"

# List of MetaAI models
META_AI_MODELS = [
    "llama3.1:8b-instruct-q6_K",
    "llama3.1:70b-instruct-q6_K",
    "llama3.3:70b-instruct-q6_K"
]

# Parameters for the model
CONFIG = {
    'seed': 42,
    'temperature': 0.8,
    'num_predict': 128
}

PROMPT_TEMPLATE = """Analyze the following text for harmful content in the German language. If the text is not in German, first translate it into German before performing the analysis. Provide your results with explanations.

Steps to Perform:

Check the language of the input text.
If the text is not in German, translate it into German.

Analyze the text for:


Flags: Check for Fake News, Hate Speech, or Toxicity (if there are mutiple flag then output the most prominent one).

Provide a detailed explanation of your analysis, referring to specific linguistic cues.
Please translate

Output Format:
•  Translated Text (if applicable): Insert translated text
•  Flags: Fake News/Hate Speech/Toxicity
•  Explanation: Provide reasoning based on linguistic patterns
"""



def process_tweetquery(tweet):
    print(f"Processing tweet: {tweet}")
    request_payload = {
        "model": META_AI_MODELS[2],  # Selecting a specific MetaAI model
        "messages": [
            {"role": "system", "content": PROMPT_TEMPLATE},
            {"role": "user", "content": tweet}
        ],
        "options": CONFIG
    }

    try:
        # Sending the request
        response = requests.post(API_URL, json=request_payload)
        response_data = response.json()
        return response_data.get("response", "No response received.")
    except Exception as error:
        return f"Error occurred: {error}"

if __name__ == "__main__":
    while True:
        user_input = input("Enter a tweet to classify (type 'exit' to quit): ")
        if user_input.lower() == "exit":
            print("Exiting the program.")
            break

        result = process_tweetquery(user_input)
        print("#### Classification Result ####")
        print(result)
        print("################################")